"""Unit tests for the M3.1 maildev helper.

The helper polls MailDev's HTTP API to extract the magic-link verify
URL from the most recent message. The round-trip integration is
covered by the E2E test (``tests/e2e/test_magic_link_e2e.py`` —
currently skipped because M3 backend wiring is missing, see issue
tracked separately); these tests pin the helper's pure logic
(regex matching, polling semantics, timeout behaviour) deterministically
with mocked HTTP.

Hard rules honoured:

- apap-testing HR-10 (no ``time.sleep``): tests use ``monkeypatch`` to
  neutralise the helper's sleep calls so the suite stays sub-second.
- apap-testing HR-15 (no orphan tests): this file is discovered by
  the default pytest run (``tests/`` is not in ``--ignore``) and the
  tests have no external prerequisites beyond ``httpx`` (already a
  runtime dep).
"""
from __future__ import annotations

from typing import Any
from unittest.mock import patch

import httpx
import pytest

from tests.e2e._maildev_helper import VERIFY_URL_RE, read_latest_verify_url

# --- helpers --------------------------------------------------------------


def _msg_with_body(body: str) -> dict[str, Any]:
    """MailDev ``/api/v2/messages`` wraps the body inside ``Content.Body``."""
    return {"Content": {"Body": body}}


def _msg_with_text(text: str) -> dict[str, Any]:
    """Some SMTP clients (or older MailDev versions) expose ``Text`` only."""
    return {"Text": text}


def _mock_get_factory(responses: list[tuple[int, list[dict[str, Any]]]]):
    """Return a ``side_effect`` callable that emits canned responses in order.

    Each entry is ``(status_code, messages_list)``. When the list is
    exhausted, subsequent calls return ``HTTP 200`` with an empty list
    (simulating "no message yet, keep polling").

    Uses a closure-counter instead of ``unittest.mock.call_args`` to
    stay independent of the mock framework's internal bookkeeping.
    """
    counter = {"idx": 0}

    def side_effect(url: str, timeout: float = 2.0) -> httpx.Response:  # noqa: ARG001
        idx = counter["idx"]
        counter["idx"] += 1
        if idx < len(responses):
            status, messages = responses[idx]
        else:
            status, messages = 200, []
        request = httpx.Request("GET", url)
        return httpx.Response(status_code=status, json=messages, request=request)

    return side_effect


# --- VERIFY_URL_RE --------------------------------------------------------


class TestVerifyUrlRegex:
    """The regex is the heart of the helper: a false match (a URL with
    the right shape but the wrong path) sends the browser to the wrong
    place and silently breaks the round-trip."""

    def test_matches_https_url_with_hex_token(self) -> None:
        url = "https://apap.romancaba.com/auth/magic/verify?token=abc123def456"
        m = VERIFY_URL_RE.search(url)
        assert m is not None
        assert m.group(0) == url

    def test_matches_http_url_with_token(self) -> None:
        url = "http://localhost:8000/auth/magic/verify?token=0123456789abcdef"
        assert VERIFY_URL_RE.search(url).group(0) == url  # type: ignore[union-attr]

    def test_matches_token_with_underscore_and_dash(self) -> None:
        # tokens generated by ``secrets.token_urlsafe`` include ``_`` and ``-``;
        # we want the regex to match them even though ``secrets.token_hex`` (the
        # current M1 producer) only emits hex.
        url = "https://example.com/auth/magic/verify?token=abc_DEF-123"
        assert VERIFY_URL_RE.search(url).group(0) == url  # type: ignore[union-attr]

    def test_rejects_url_without_token_param(self) -> None:
        assert VERIFY_URL_RE.search("https://example.com/auth/magic/verify") is None

    def test_rejects_url_with_different_path(self) -> None:
        assert (
            VERIFY_URL_RE.search("https://example.com/something/else?token=abc") is None
        )

    def test_rejects_url_with_empty_token(self) -> None:
        assert (
            VERIFY_URL_RE.search("https://example.com/auth/magic/verify?token=") is None
        )

    def test_extracts_url_from_prose(self) -> None:
        prose = (
            "Hola,\nHaz click aqui para verificar: "
            "https://apap.romancaba.com/auth/magic/verify?token=abc123 "
            "y podras entrar.\n"
        )
        m = VERIFY_URL_RE.search(prose)
        assert m is not None
        assert m.group(0).startswith("https://apap.romancaba.com/auth/magic/verify")
        assert "token=abc123" in m.group(0)


# --- read_latest_verify_url -----------------------------------------------


class TestReadLatestVerifyUrl:
    """Polling semantics: return the first message that contains a
    verify URL, or raise ``AssertionError`` after the timeout."""

    def test_returns_url_from_first_message(self, monkeypatch: pytest.MonkeyPatch) -> None:
        body = "Click https://apap.romancaba.com/auth/magic/verify?token=abc to login."
        monkeypatch.setattr("time.sleep", lambda _seconds: None)
        with patch("httpx.get", side_effect=_mock_get_factory([(200, [_msg_with_body(body)])])):
            url = read_latest_verify_url("http://maildev:8025", timeout_seconds=1.0)
        assert url == "https://apap.romancaba.com/auth/magic/verify?token=abc"

    def test_falls_back_to_text_field_when_content_body_empty(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # ``Content.Body`` empty -> helper must read ``Text`` instead.
        text = "Verify at https://example.com/auth/magic/verify?token=zzz"
        msg = _msg_with_text(text)
        msg["Content"] = {"Body": ""}
        monkeypatch.setattr("time.sleep", lambda _seconds: None)
        with patch("httpx.get", side_effect=_mock_get_factory([(200, [msg])])):
            url = read_latest_verify_url("http://maildev:8025", timeout_seconds=1.0)
        assert "token=zzz" in url

    def test_polls_until_message_arrives(self, monkeypatch: pytest.MonkeyPatch) -> None:
        # First two calls return empty; third call returns the message.
        # The helper must not give up after an empty batch.
        body = "https://example.com/auth/magic/verify?token=hello"
        monkeypatch.setattr("time.sleep", lambda _seconds: None)
        responses = [
            (200, []),
            (200, []),
            (200, [_msg_with_body(body)]),
        ]
        with patch("httpx.get", side_effect=_mock_get_factory(responses)):
            url = read_latest_verify_url("http://maildev:8025", timeout_seconds=2.0)
        assert "token=hello" in url

    def test_raises_assertion_when_no_message_within_timeout(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr("time.sleep", lambda _seconds: None)
        with patch("httpx.get", side_effect=_mock_get_factory([(200, [])])):
            with pytest.raises(AssertionError, match="no magic-link message arrived"):
                read_latest_verify_url("http://maildev:8025", timeout_seconds=0.5)

    def test_continues_after_http_error(self, monkeypatch: pytest.MonkeyPatch) -> None:
        # First call: HTTP 500 (server blip). Second call: message arrives.
        # The helper must not give up on a transient 5xx; it should retry.
        body = "https://example.com/auth/magic/verify?token=after500"
        monkeypatch.setattr("time.sleep", lambda _seconds: None)
        responses = [
            (500, []),
            (200, [_msg_with_body(body)]),
        ]
        with patch("httpx.get", side_effect=_mock_get_factory(responses)):
            url = read_latest_verify_url("http://maildev:8025", timeout_seconds=2.0)
        assert "token=after500" in url

    def test_retries_when_first_message_has_no_verify_url(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # First message: no verify URL. Helper must not return early;
        # it should retry. Second call returns a fresh batch with the URL.
        body = "https://example.com/auth/magic/verify?token=fresh"
        monkeypatch.setattr("time.sleep", lambda _seconds: None)
        responses = [
            (200, [_msg_with_text("No link here, just chatter.")]),
            (200, [_msg_with_body(body)]),
        ]
        with patch("httpx.get", side_effect=_mock_get_factory(responses)):
            url = read_latest_verify_url("http://maildev:8025", timeout_seconds=2.0)
        assert "token=fresh" in url
