-- Issue #7 — create the ``tarea`` table for the common task engine.
--
-- Idempotent pattern: ``CREATE TABLE IF NOT EXISTS`` allows re-running
-- apply_sql_migrations on an already-migrated database without errors.
--
-- The table stores both manual tasks (created by operators) and
-- automatic tasks (generated by the rule engine). The ``tipo`` enum
-- distinguishes the origin; ``origen`` captures the trigger source.
--
-- Columns:
--   id              UUID primary key
--   tipo            task type (manual vs automatic subtypes)
--   origen          trigger source (dashboard_manual, regla_salud, …)
--   prioridad       business priority
--   estado          lifecycle state
--   responsable_id  FK to voluntarios (nullable — unassigned tasks)
--   vencimiento_at  optional deadline
--   vinculo_tipo    what the task is linked to (animal, adopcion, …)
--   vinculo_id      UUID of the linked entity
--   metadata        JSONB for extensible per-type payload
--   created_at / updated_at timestamps
--
-- Indexes for the most common filter paths:
--   idx_tarea_estado        — filter by estado (pending, in-progress, …)
--   idx_tarea_responsable   — filter by assigned volunteer
--   idx_tarea_vencimiento  — filter by deadline (scheduler, dashboard)
--   idx_tarea_vinculo       — (vinculo_tipo, vinculo_id) for lookups

CREATE TABLE IF NOT EXISTS tarea (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tipo            TEXT        NOT NULL DEFAULT 'manual',
    origen          TEXT        NOT NULL DEFAULT 'dashboard_manual',
    prioridad       TEXT        NOT NULL DEFAULT 'normal',
    estado          TEXT        NOT NULL DEFAULT 'pendiente',
    responsable_id  UUID        NULL,
    vencimiento_at  TIMESTAMPTZ NULL,
    vinculo_tipo    TEXT        NULL,
    vinculo_id      UUID        NULL,
    metadata        JSONB       NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_tarea_tipo
        CHECK (tipo IN (
            'manual',
            'automatica_vacuna',
            'automatica_tratamiento',
            'automatica_revision',
            'automatica_esterilizacion',
            'automatica_microchip',
            'automatica_desparasitacion',
            'automatica_seguimiento_acogida',
            'automatica_seguimiento_post_adopcion',
            'automatica_documentacion',
            'automatica_administrativa'
        )),
    CONSTRAINT chk_tarea_origen
        CHECK (origen IN (
            'dashboard_manual',
            'regla_salud',
            'regla_acogida',
            'regla_adopcion',
            'regla_documentacion',
            'regla_administrativa'
        )),
    CONSTRAINT chk_tarea_prioridad
        CHECK (prioridad IN ('baja', 'normal', 'alta', 'urgente')),
    CONSTRAINT chk_tarea_estado
        CHECK (estado IN ('pendiente', 'en_progreso', 'completada', 'cancelada', 'vencida')),
    CONSTRAINT chk_tarea_vinculo_tipo
        CHECK (vinculo_tipo IS NULL OR vinculo_tipo IN (
            'animal', 'voluntario', 'entrada', 'acogida', 'adopcion', 'documento'
        ))
);

CREATE INDEX IF NOT EXISTS idx_tarea_estado        ON tarea (estado);
CREATE INDEX IF NOT EXISTS idx_tarea_responsable  ON tarea (responsable_id);
CREATE INDEX IF NOT EXISTS idx_tarea_vencimiento  ON tarea (vencimiento_at) WHERE vencimiento_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tarea_vinculo      ON tarea (vinculo_tipo, vinculo_id) WHERE vinculo_tipo IS NOT NULL;
