BeforeAll {
    $script:Dispatcher=Join-Path (Split-Path -Parent $PSScriptRoot) 'Invoke-AIModelProfile.ps1'
    $script:Fixture=Join-Path $PSScriptRoot 'fixtures\opencode.json'
    function script:New-Ctx {
        $r=Join-Path ([IO.Path]::GetTempPath()) "ampm-$([guid]::NewGuid().ToString('N'))";New-Item -ItemType Directory $r|Out-Null
        $ocRoot=Join-Path $r '.config\opencode';New-Item -ItemType Directory $ocRoot -Force|Out-Null;$oc=Join-Path $ocRoot 'opencode.json';Copy-Item $script:Fixture $oc;$d=Get-Content -Raw $oc|ConvertFrom-Json -AsHashtable;$d.agent['sdd-orchestrator-and']=@{model='old/model'};$d.agent['sdd-orchestrator-and-fallback']=@{model='old/model'};if(-not$d.agent.ContainsKey('sdd-propose')){$d.agent['sdd-propose']=@{model='old/model'}};$d|ConvertTo-Json -Depth 100|Set-Content $oc
        $pg=Join-Path $r '.pi\gentle-ai';New-Item -ItemType Directory $pg -Force|Out-Null;$pi=Join-Path $pg 'models.json';'{"existing":true,"models":{"pi-only":"keep/model"}}'|Set-Content $pi;$pp=Join-Path $pg 'profiles';New-Item -ItemType Directory $pp|Out-Null;$par=Join-Path $r '.pi\agent';New-Item -ItemType Directory $par -Force|Out-Null;$pa=Join-Path $par 'agents';New-Item -ItemType Directory $pa|Out-Null;"---`nmodel: old/model`nkeep: yes`n---"|Set-Content (Join-Path $pa 'sdd-proposal.md');$ps=Join-Path $par 'settings.json';'{"theme":"keep"}'|Set-Content $ps
        $cx=Join-Path $r '.codex';New-Item -ItemType Directory $cx|Out-Null;foreach($n in 'strong','mid','cheap'){"# keep`nmodel = `"old`" # root`nmodel_reasoning_effort = `"low`"`n[profile.nested]`nmodel = `"nested-keep`" # nested`n"|Set-Content (Join-Path $cx "sdd-$n.config.toml")}
        $pf=Join-Path $r 'profile.json';@{schemaVersion='ai-model-profile/v1';name='Test';models=@{'gentle-orchestrator'='openai/gpt-5.6-sol';'sdd-apply'='openai/gpt-5.6-terra';'sdd-propose'='openai/gpt-5.6-terra'};pi=@{providerMap=@{openai='openai-codex'}};codex=@{strong=@{model='gpt-5.6-sol';reasoningEffort='high'};mid=@{model='gpt-5.6-terra';reasoningEffort='medium'};cheap=@{model='gpt-5.6-luna';reasoningEffort='low'}}}|ConvertTo-Json -Depth 20|Set-Content $pf
        [pscustomobject]@{root=$r;openCode=$oc;pi=$pi;piProfiles=$pp;piAgents=$pa;piSettings=$ps;codex=$cx;profile=$pf;backup=(Join-Path $r '.gentle-ai\backups\model-profiles')}
    }
    function script:Invoke-D($c,[hashtable]$x){$oldHome=$env:HOME;$oldProfile=$env:USERPROFILE;$oldConfig=$env:OPENCODE_CONFIG;try{$env:HOME=$c.root;$env:USERPROFILE=$c.root;$env:OPENCODE_CONFIG=$c.openCode;$a=@{OpenCodePath=$c.openCode;PiPath=$c.pi;PiProfilesRoot=$c.piProfiles;PiAgentsRoot=$c.piAgents;PiSettingsPath=$c.piSettings;CodexRoot=$c.codex;BackupRoot=$c.backup;InternalNoCatalog=$true};foreach($k in $x.Keys){$a[$k]=$x[$k]};& $script:Dispatcher @a}finally{$env:HOME=$oldHome;$env:USERPROFILE=$oldProfile;$env:OPENCODE_CONFIG=$oldConfig}}
    function script:Reseal($p){(Get-FileHash -LiteralPath $p).Hash|Set-Content "$p.sha256"}
}
Describe 'Invoke-AIModelProfile isolated transaction' {
    It 'previews without writes' {$c=New-Ctx;try{$h=(Get-FileHash $c.openCode).Hash;$r=Invoke-D $c @{Profile=$c.profile}|ConvertFrom-Json;$r.operation|Should -Be preview;(Get-FileHash $c.openCode).Hash|Should -Be $h}finally{Remove-Item $c.root -Recurse -Force}}
    It 'applies and byte-exactly rolls back BOM and non-UTF8 targets' {$c=New-Ctx;try{$body=[Text.Encoding]::Unicode.GetBytes('{"theme":"x"}');$bytes=[byte[]](0xFF,0xFE)+$body;[IO.File]::WriteAllBytes($c.piSettings,$bytes);$a=Invoke-D $c @{Profile=$c.profile;Targets=@('Pi');Apply=$true}|ConvertFrom-Json;$null=Invoke-D $c @{RollbackManifest=$a.rollbackManifest;Targets=@('Pi');Apply=$true};[Convert]::ToBase64String([IO.File]::ReadAllBytes($c.piSettings))|Should -Be ([Convert]::ToBase64String($bytes))}finally{Remove-Item $c.root -Recurse -Force}}
    It 'merges unowned Pi profile-library state' {$c=New-Ctx;try{'{"owner":"keep","models":{"custom":"keep/model"}}'|Set-Content (Join-Path $c.piProfiles 'Test.json');$null=Invoke-D $c @{Profile=$c.profile;Targets=@('Pi');Apply=$true};$p=Get-Content -Raw (Join-Path $c.piProfiles 'Test.json')|ConvertFrom-Json;$p.owner|Should -Be keep;$p.models.custom|Should -Be 'keep/model'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'mutates only root TOML owned keys' {$c=New-Ctx;try{$null=Invoke-D $c @{Profile=$c.profile;Targets=@('Codex');Apply=$true};$t=Get-Content -Raw (Join-Path $c.codex 'sdd-strong.config.toml');$t|Should -Match 'model = "gpt-5.6-sol" # root';$t|Should -Match 'model = "nested-keep" # nested'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'rejects unsafe profile and agent names' {$c=New-Ctx;try{$d=Get-Content -Raw $c.profile|ConvertFrom-Json -AsHashtable;$d.name='../escape';$d|ConvertTo-Json -Depth 20|Set-Content $c.profile;{Invoke-D $c @{Profile=$c.profile;Targets=@('Pi')}}|Should -Throw '*Unsafe profile*';$d.name='Safe';$d.models['../agent']='openai/x';$d|ConvertTo-Json -Depth 20|Set-Content $c.profile;{Invoke-D $c @{Profile=$c.profile;Targets=@('Pi')}}|Should -Throw '*Unsafe*agent*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'rejects reparse traversal for derived Pi profile paths' {$c=New-Ctx;try{$outside=Join-Path $c.root 'outside';New-Item -ItemType Directory $outside|Out-Null;Remove-Item $c.piProfiles;New-Item -ItemType SymbolicLink -Path $c.piProfiles -Target $outside|Out-Null;{Invoke-D $c @{Profile=$c.profile;Targets=@('Pi')}}|Should -Throw '*Reparse traversal*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'requires explicit rollback targets' {$c=New-Ctx;try{$a=Invoke-D $c @{Profile=$c.profile;Targets=@('OpenCode');Apply=$true}|ConvertFrom-Json;{Invoke-D $c @{RollbackManifest=$a.rollbackManifest;Apply=$true}}|Should -Throw '*explicit -Targets*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'rejects correctly resealed forged arbitrary paths and unknown roles' {$c=New-Ctx;try{$a=Invoke-D $c @{Profile=$c.profile;Targets=@('OpenCode');Apply=$true}|ConvertFrom-Json;$m=Get-Content -Raw $a.rollbackManifest|ConvertFrom-Json -AsHashtable;$m.files[0].path=$c.profile;$m.files[0].role='forged';$m|ConvertTo-Json -Depth 30|Set-Content $a.rollbackManifest;Reseal $a.rollbackManifest;{Invoke-D $c @{RollbackManifest=$a.rollbackManifest;Targets=@('OpenCode');Apply=$true}}|Should -Throw '*unknown role*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'rejects a correctly resealed known role with an arbitrary target path' {$c=New-Ctx;try{$a=Invoke-D $c @{Profile=$c.profile;Targets=@('OpenCode');Apply=$true}|ConvertFrom-Json;$m=Get-Content -Raw $a.rollbackManifest|ConvertFrom-Json -AsHashtable;$m.files[0].path=$c.profile;$m|ConvertTo-Json -Depth 30|Set-Content $a.rollbackManifest;Reseal $a.rollbackManifest;{Invoke-D $c @{RollbackManifest=$a.rollbackManifest;Targets=@('OpenCode');Apply=$true}}|Should -Throw '*target path mismatch*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'rejects a correctly resealed backup escape' {$c=New-Ctx;try{$a=Invoke-D $c @{Profile=$c.profile;Targets=@('OpenCode');Apply=$true}|ConvertFrom-Json;$m=Get-Content -Raw $a.rollbackManifest|ConvertFrom-Json -AsHashtable;$m.files[0].backup=$c.profile;$m|ConvertTo-Json -Depth 30|Set-Content $a.rollbackManifest;Reseal $a.rollbackManifest;{Invoke-D $c @{RollbackManifest=$a.rollbackManifest;Targets=@('OpenCode');Apply=$true}}|Should -Throw '*escapes canonical root*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'rejects duplicate roles' {$c=New-Ctx;try{$a=Invoke-D $c @{Profile=$c.profile;Targets=@('OpenCode');Apply=$true}|ConvertFrom-Json;$m=Get-Content -Raw $a.rollbackManifest|ConvertFrom-Json -AsHashtable;$m.files+=@($m.files[0]);$m|ConvertTo-Json -Depth 30|Set-Content $a.rollbackManifest;Reseal $a.rollbackManifest;{Invoke-D $c @{RollbackManifest=$a.rollbackManifest;Targets=@('OpenCode');Apply=$true}}|Should -Throw '*duplicate role*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'routes tier apply through a pending dispatcher manifest' {$c=New-Ctx;try{$a=Invoke-D $c @{Provider='openai';Tier='cheap';Apply=$true;SkipRuntimeValidation=$true}|ConvertFrom-Json;$a.operation|Should -Be apply;$a.rollbackManifest|Should -Exist;(Get-Content -Raw $a.rollbackManifest|ConvertFrom-Json).state|Should -Be applied;$null=Invoke-D $c @{RollbackManifest=$a.rollbackManifest;Targets=@('OpenCode');Apply=$true}}finally{Remove-Item $c.root -Recurse -Force}}
    It 'strips internal candidate bytes from public tier output' {$c=New-Ctx;try{$a=Invoke-D $c @{Provider='openai';Tier='cheap';SkipRuntimeValidation=$true}|ConvertFrom-Json;$a.changes[0].PSObject.Properties.Name|Should -Not -Contain candidateBase64}finally{Remove-Item $c.root -Recurse -Force}}
    It 'rejects explicit credential targets and target escapes' {$c=New-Ctx;try{$auth=Join-Path $c.root '.config\opencode\auth.json';New-Item -ItemType File -Path $auth -Force|Out-Null;{Invoke-D $c @{Profile=$c.profile;OpenCodePath=$auth}}|Should -Throw '*Credential-sensitive*';$outside=Join-Path $c.root 'opencode.json';Copy-Item $c.openCode $outside;{Invoke-D $c @{Profile=$c.profile;OpenCodePath=$outside}}|Should -Throw '*escapes canonical root*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'rejects reparse traversal for every explicit writable root' {$c=New-Ctx;try{$outside=Join-Path $c.root 'outside-root';New-Item -ItemType Directory $outside|Out-Null;Remove-Item $c.codex -Recurse;New-Item -ItemType SymbolicLink -Path $c.codex -Target $outside|Out-Null;{Invoke-D $c @{Profile=$c.profile}}|Should -Throw '*Reparse traversal*'}finally{Remove-Item $c.root -Recurse -Force}}
    It 'aggregates tier restoration failures and records the original apply error' {$c=New-Ctx;try{$err=$null;try{Invoke-D $c @{Provider='openai';Tier='cheap';Apply=$true;SkipRuntimeValidation=$true;InternalFailApplyPath=$c.openCode;InternalFailRestorePaths=@($c.openCode)}|Out-Null}catch{$err=$_.Exception.Message};$err|Should -Match 'Injected apply failure';$err|Should -Match 'Restoration failures';$m=Get-ChildItem $c.backup -Filter rollback.json -Recurse|Select-Object -First 1|Get-Content -Raw|ConvertFrom-Json;$m.state|Should -Be failed;$m.applyErrors[0]|Should -Match 'Injected apply failure';$m.rollbackErrors.Count|Should -Be 1}finally{Remove-Item $c.root -Recurse -Force}}
}
