"""Protocol for magic-link login (M1, issue #641).

Magic links are one-time tokens for passwordless login and password
reset. The raw token is generated by the server; only its SHA-256
hash is stored in the DB so a DB leak does not expose live tokens.

The flow:
1. Operator (or SMTP future epic) generates a token for an email.
2. The token is delivered to the user via a trusted channel
   (operator logs it; the user is told in person).
3. The user clicks ``/api/auth/magic?token=...``.
4. The server consumes the token: returns the email if the hash matches,
   not used, not expired. Marks ``used_at = now()`` atomically.
5. The server emits a session cookie for the user.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MagicLinkPort(Protocol):
    """One-time tokens for passwordless login and password reset."""

    def create_token(
        self,
        email: str,
        *,
        purpose: str = "login",
        ttl_seconds: int = 1800,
    ) -> str:
        """Generate a fresh magic-link token for ``email`` and return the
        raw value. The caller is responsible for delivering the token
        to the user (operator log during MVP, SMTP in a future epic).

        Stores a SHA-256 of the token so a DB leak does not expose live
        tokens. The raw token never touches persistent storage.

        ``purpose`` differentiates the consumer (login vs password_reset).
        Tokens are not interchangeable: a token issued for login
        cannot reset a password.
        """
        ...

    def consume_token(self, raw_token: str) -> str | None:
        """Return the email if the token is valid; mark as used.

        Valid means: the hash exists, the token has not been used
        before, and the TTL has not expired. Returns ``None`` for any
        failure (invalid, used, expired) so the caller cannot
        distinguish.
        """
        ...

    def list_active(self) -> list[dict[str, Any]]:
        """Return all unexpired, unused tokens for the admin panel."""
        ...


__all__ = ["MagicLinkPort"]
