"""Domain entity for a TipoContrato (contract-template type) catalog entry.

P1 fidelity (legacy ``TbPlantillas``): one row per *plantilla de contrato*
— a contract template generated by the protectora. The legacy columns
``InicialDocumento``, ``NombreTabla``, ``NombreCampo`` map to
``iniciales``, ``tabla_legacy``, ``campo_legacy`` so the future template
engine (Fase 7 of ``docs/roadmap.md``) can pick the right prefix and
write to the right column without joining the legacy again.

The natural key is ``codigo`` (the contract type's name in the legacy,
Spanish spelling). ``tabla_legacy`` and ``campo_legacy`` are ``None`` for
contract types that the legacy has not yet wired to a specific column
(e.g. ``'Ficha de Seguimiento'``); that is a forward-extension gap, not
a domain anomaly.
"""


from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class TipoContrato:
    """Domain entity for a contract-template type in the catalog.

    Attributes:
        id: Server-assigned UUID; opaque to the domain.
        codigo: Natural key — the contract type's name in the legacy
            (Spanish spelling).
        nombre: Human-readable display name; equals ``codigo`` for the
            current 8-row seed.
        iniciales: Comma-separated initial-letters codes from the legacy
            ``InicialDocumento`` column (e.g. ``'AC;AT'`` for
            ``'Acogida'``). ``None`` when the legacy did not carry one.
        descripcion: Free-text description of the contract type.
        tabla_legacy: Legacy table name where the per-record contract
            number lives (``NombreTabla`` column). ``None`` when the
            legacy has not wired a column for this type.
        campo_legacy: Legacy column name where the per-record contract
            number lives (``NombreCampo`` column). ``None`` when the
            legacy has not wired a column for this type.
        activo: ``True`` when the row is live.
        orden: Display order (lower first); ``None`` when unset.
    """

    id: str
    codigo: str
    nombre: str
    iniciales: str | None
    descripcion: str | None
    tabla_legacy: str | None
    campo_legacy: str | None
    activo: bool
    orden: int | None


__all__ = ["TipoContrato"]
